********************************************************************;
*  COMBINE ALL ROLL-UP DATASETS INTO ONE                           *;
********************************************************************;

DATA MCBSDATA.ROLLUP_ALL;
MERGE MCBSDATA.TEMP_DOS 
      MCBSDATA.TEMP_STR 
      MCBSDATA.TEMP_PKG;
BY BN;
RUN;
/*
DATA OLDNAMES;
SET MCBSDATA.THRUBDMS (KEEP = NEWFDA);
RENAME NEWFDA=NFDA_NM;
RUN;


PROC PRINT; WHERE NFDA_NM IN 
('ADALAT','ANADRINE DM','ANUZONE-HC');
TITLE 'FIRST';
RUN;

PROC SORT DATA=OLDNAMES NODUPKEY;
BY NFDA_NM;
RUN;

DATA THISYEAR(RENAME=(NEWFDA=NFDA_NM));
SET MCBSDATA.ROLLUP_ALL;
RUN;

PROC PRINT; WHERE NFDA_NM IN ('ADALAT','ANADRINE DM',
'ANUZONE-HC');
TITLE 'SECOND';
RUN;

PROC SORT DATA=THISYEAR NODUPKEY;
BY NFDA_NM;
RUN;

DATA     FIX(KEEP=NFDA_NM);
MERGE OLDNAMES (IN=A) THISYEAR (IN=B);
BY NFDA_NM;
IF A;
IF NOT B THEN OUTPUT     FIX;
RUN;

DATA FIX; SET FIX;
NFDA_NM2=NFDA_NM;
RUN;


PROC EXPORT DATA= FIX 
            OUTFILE= "&location.FDA_NEEDFIX_&CurrYear..xls" 
            DBMS=EXCEL REPLACE;
     SHEET="NEEDFIX"; 
RUN;

*/
