********************************************************************;
*  PROCESS STRENGTH SUBROUTINE                                     *;
********************************************************************;
PROC_STR:;

IF I_STRU1 IN('1','2','3','4','5') THEN DO;
IDX = I_STRU1;
UNITCNV1 = UNIT1(IDX);UNITCNV2 = UNIT2(IDX);
END;

STR_FD = 0;

IF S1_CTR(1) EQ . OR (S1_CTR(1) EQ 0 AND S1_CTR(2) EQ 0) THEN DO;
GEN = 1;

RETURN;
END;
********************************************************************;
*  PROCESSING IS ONLY APPLICABLE TO DOSAGE FORM CODES: 1 AND 10    *;
*                                                                  *;
*  1) MATCH ON STRENGTH NUMBER AND UNITS                           *;
*  2) MATCH ON STRENGTH NUMBER                                     *;
*  3) MATCH ON STRENGTH UNITS                                      *;
*  4) IF DOSAGE FORM CODE WAS PREVIOUSLY MATCHED FOR THE PROCESSED *;
*     FDA NAME, THEN RANDOMLY GENERATE THE STRENGTH NUMBER/UNITS   *;
********************************************************************;
IF NOT DOS_FD THEN DO;
DOS_FL = 1;
I_DCODE = 1;
END;

DO Y=1 TO 2;
IF I_DCODE EQ 1 THEN
IDX = 1;
ELSE
IDX = 2;

IF I_STRN1 GT 0 AND I_STRU1 IN('1','2','3','4','5','91') THEN DO;
DO X=1 TO S1_CTR(IDX);
IF I_CMPFL THEN DO;
IF ((I_STRN1  EQ S1_NUM(IDX,X,1)   AND I_STRN2  EQ S1_NUM(IDX,X,2))  
  OR(I_STRN2  EQ S1_NUM(IDX,X,1)   AND I_STRN1  EQ S1_NUM(IDX,X,2))) THEN DO;
IF I_STRU1 NE '91' THEN DO;
IF (UNITCNV1 EQ S1_UNT(IDX,X,1)   OR
UNITCNV1 EQ S1_UNT(IDX,X,2)   OR
UNITCNV2 EQ S1_UNT(IDX,X,1)   OR
UNITCNV2 EQ S1_UNT(IDX,X,2))  THEN DO;
OTC_CD   = S1_OTC(IDX,X);
TEC_CD   = S1_TEC(IDX,X);
AWP      = S1_PR(IDX,X);
STRENGTH = S1_TP(IDX,X);
DOSAGE   = S1_DOS(IDX,X);
I_DCODE  = S1_COD(IDX,X);
STR_FD   = X;

GO TO BRK_STR;
END;
END;
ELSE DO;
IF S1_UNT(IDX,X,1) NOT
IN('MCG','MG','G','GX','MEQ','GM') THEN DO;
OTC_CD   = S1_OTC(IDX,X);
TEC_CD   = S1_TEC(IDX,X);
AWP      = S1_PR(IDX,X);
STRENGTH = S1_TP(IDX,X);
DOSAGE   = S1_DOS(IDX,X);
I_DCODE  = S1_COD(IDX,X);
STR_FD   = X;

GO TO BRK_STR;
END;
END;
END;
END;
ELSE DO;
IF I_STRN1 EQ S1_NUM(IDX,X,1) OR
I_STRN1 EQ S1_NUM(IDX,X,2) THEN DO;
IF I_STRU1 NE '91' THEN DO;
IF (UNITCNV1 EQ S1_UNT(IDX,X,1)   OR
UNITCNV1 EQ S1_UNT(IDX,X,2)   OR
UNITCNV2 EQ S1_UNT(IDX,X,1)   OR
UNITCNV2 EQ S1_UNT(IDX,X,2))  THEN DO;
OTC_CD   = S1_OTC(IDX,X);
TEC_CD   = S1_TEC(IDX,X);
AWP      = S1_PR(IDX,X);
STRENGTH = S1_TP(IDX,X);
DOSAGE   = S1_DOS(IDX,X);
I_DCODE  = S1_COD(IDX,X);
STR_FD   = X;

GO TO BRK_STR;
END;
END;
ELSE DO;
IF S1_UNT(IDX,X,1) NOT
IN('MCG','MG','G','GX','MEQ','GM') THEN DO;
OTC_CD   = S1_OTC(IDX,X);
TEC_CD   = S1_TEC(IDX,X);
AWP      = S1_PR(IDX,X);
STRENGTH = S1_TP(IDX,X);
DOSAGE   = S1_DOS(IDX,X);
I_DCODE  = S1_COD(IDX,X);
STR_FD   = X;

GO TO BRK_STR;
END;
END;
END;
END;
END;
END;

IF I_STRN1 GT 0 THEN DO;
DO X=1 TO S1_CTR(IDX);
IF I_CMPFL THEN DO;
IF ((I_STRN1  EQ S1_NUM(IDX,X,1)   AND
I_STRN2  EQ S1_NUM(IDX,X,2))  OR
(I_STRN2  EQ S1_NUM(IDX,X,1)   AND
I_STRN1  EQ S1_NUM(IDX,X,2))) THEN DO;
OTC_CD   = S1_OTC(IDX,X);
TEC_CD   = S1_TEC(IDX,X);
AWP      = S1_PR(IDX,X);
STRENGTH = S1_TP(IDX,X);
DOSAGE   = S1_DOS(IDX,X);
I_DCODE  = S1_COD(IDX,X);
STR_FD   = X;
STR_FL   = 1;

GO TO BRK_STR;
END;
END;
ELSE DO;
IF (I_STRN1  EQ S1_NUM(IDX,X,1)  OR
I_STRN1  EQ S1_NUM(IDX,X,2)) THEN DO;
OTC_CD   = S1_OTC(IDX,X);
TEC_CD   = S1_TEC(IDX,X);
AWP      = S1_PR(IDX,X);
STRENGTH = S1_TP(IDX,X);
DOSAGE   = S1_DOS(IDX,X);
I_DCODE  = S1_COD(IDX,X);
STR_FD   = X;
STR_FL   = 1;

GO TO BRK_STR;
END;
END;
END;
END;

IF I_STRU1 IN('1','2','3','4','5','91') THEN DO;
DO X=1 TO S1_CTR(IDX);
IF I_STRU1 NE '91' THEN DO;
IF (UNITCNV1 EQ S1_UNT(IDX,X,1)   OR
UNITCNV1 EQ S1_UNT(IDX,X,2)   OR
UNITCNV2 EQ S1_UNT(IDX,X,1)   OR
UNITCNV2 EQ S1_UNT(IDX,X,2))  THEN DO;
OTC_CD   = S1_OTC(IDX,X);
TEC_CD   = S1_TEC(IDX,X);
AWP      = S1_PR(IDX,X);
STRENGTH = S1_TP(IDX,X);
DOSAGE   = S1_DOS(IDX,X);
I_DCODE  = S1_COD(IDX,X);
STR_FD   = X;
STR_FL   = 1;

GO TO BRK_STR;
END;
END;
ELSE DO;
IF S1_UNT(IDX,X,1) NOT
IN('MCG','MG','G','GX','MEQ','GM') THEN DO;
OTC_CD   = S1_OTC(IDX,X);
TEC_CD   = S1_TEC(IDX,X);
AWP      = S1_PR(IDX,X);
STRENGTH = S1_TP(IDX,X);
DOSAGE   = S1_DOS(IDX,X);
I_DCODE  = S1_COD(IDX,X);
STR_FD   = X;
STR_FL   = 1;

GO TO BRK_STR;
END;
END;
END;
END;

IF DOS_FD THEN
GO TO BRK_STR;

DOS_FD = 0;
DOS_FL = 1;
I_DCODE = 0;
END;

BRK_STR:;

********************************************************************;
*  UNSUCCESSFUL MATCH - GENERATE STRENGTH NUMBER/UNITS IF MATCHING *;
*  DOSAGE FORM CODE, OTHERWISE GENERATE DOSAGE FORM CODE/STRENGTH  *;
********************************************************************;
IF STR_FD THEN
/* GOOD MATCH */;
ELSE IF NOT STR_FD AND DOS_FD THEN DO;
IF I_DCODE EQ 1 THEN
IDX = 1;
ELSE
IDX = 2;

MAX = S1_CT(IDX,S1_CTR(IDX),1);
STR_FL = 1;

LINK PROC_RDM;

DO X=1 TO S1_CTR(IDX);
IF RANDOM LE S1_CT(IDX,X,1) THEN DO;
OTC_CD   = S1_OTC(IDX,X);
TEC_CD   = S1_TEC(IDX,X);
AWP      = S1_PR(IDX,X);
STRENGTH = S1_TP(IDX,X);
DOSAGE   = S1_DOS(IDX,X);
STR_FD   = X;

GO TO BRK_STR1;
END;
END;
END;
ELSE
GEN = 1;

BRK_STR1:;

RETURN;

