*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
|      PROGRAM: 05_PMFORMFX                                                              |
|      UPDATED: 10/05/2012 (added pHMO)                                                  |
|  INPUT FILES: FINAL_&CURRYEAR._V2, THRUBDMS.txt, FINAL_DATA.txt                        |
| OUTPUT FILES: OUTCOMM_Y&CurrYear                                                       |
|  DESCRIPTION: Legacy description: "THIS CODE CONVERTS FORMS TO THOSE THAT ARE POSSIBLE |
|               ACCORDING TO BLUE IMPUTATION BUT COVERTS BACK THE ONES                   |
|               THAT WE BELIEVE TO BE CORRECT"                                           |
|                                                                                        |
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*;
ODS HTML CLOSE;
  ODS HTML;

OPTION MLOGIC MPRINT SYMBOLGEN COMPRESS=YES;
options nofmterr;

%LET CURRYEAR=20;
%LET LASTYEAR=19;


%let location = C:\Users\S1C3\RIC PME\MCBS\20&CURRYEAR.\PME\Data\;
libname  MCBSDATA "&location";
filename THRUBDMS "&location.THRUBDMS.txt";
filename FNL_DATA "&location.FINAL_DATA.txt";

ods rtf bodytitle file ="&location.Output\05_PMFORMFX Output - %sysfunc(DATE(),mmddyyd10.).rtf";


*** YOU HAVE TO USE ORIGINAL FILES TO CAPTURE ALL DRUGS ***;
***  AND RETAIN OTH IMPORTANT INFORMATION FOR LATER     ***;
*note: 01/29/10 now keeping PD and MA variables;
DATA GET_ALL
(KEEP=HDDM HDOPUB HDPHMO HDPRVE HDPRVI HDRX
      BASEID COSTNUM EVNTNUM GETNUM _DIFPMS _NEWRECS _PURCHPM _RECSEV _RECSPM /*_NEWDIF _NEWPM*/
     _AMTCAID _AMTCARE _AMTDISC _AMTHMO _AMTpHMO _AMTOOP _AMTOTH _AMTPRVE _AMTPRVI _AMTVA _AMTPD _AMTMA 
     _SOPCAID _SOPCARE _SOPDISC _SOPHMO _SOPpHMO _SOPOOP _SOPOTH _SOPPRVE _SOPPRVI _SOPVA _SOPPD _SOPMA
     ISOPCAID ISOPCARE ISOPDISC ISOPHMO ISOPpHMO ISOPOOP ISOPOTH ISOPPRVE ISOPPRVI ISOPVA ISOPPD ISOPMA
     NUMLINKS NUMSAME PMEDNAME ROUND TOTALCHG UTILNUM SUMHPM SUMPM SUMPMS
     PMFORMMC AMTUNIT STRNUNIT AMTNUM STRNNUM TABNUM ID PMCOND PMKNWNM);
LENGTH EVNTNUM $3. pmformmc 8. amtunit 3. strnunit 8.;

SET MCBSDATA.FINAL_&CURRYEAR._V2 (RENAME=(PMFORMMC=FORM STRNUNIT=STRNU AMTUNIT=AMTU));



*LENGTH PEVNTNUM $3.;
*PEVNTNUM=EVNTNUM;
 

ID = BASEID||EVNTNUM||ROUND||UTILNUM;
PMFORMMC='  ';
AMTUNIT='  ';
STRNUNIT='  ';
PMFORMMC=FORM;
STRNUNIT=STRNU;
AMTUNIT=AMTU;

RUN;
 
PROC SORT DATA=GET_ALL NODUPKEY; BY ID; RUN;



DATA THRU;
INFILE THRUBDMS TRUNCOVER;
INPUT  
  PMROID   $  1-13
  BN   $ 14-73
  UTILNUM  $ 99-102; /* UPDATED INPUT TO REFLECT LENGTH CHANGE*/
ID=PMROID||UTILNUM;
RUN;


PROC SORT DATA=THRU NODUPKEY dupout=duptest; BY ID;RUN;

*** MERGE TO ORIGINAL FILES, THIS WILL NOW ELIMINATE NONDRUGS FROM;
** THOSE FILES;
DATA DRUGONLY WHY;   /* THERE SHOULD BE NONE IN WHY */
MERGE THRU    (IN=A) 
      GET_ALL (IN=B);
BY ID;
IF A;
IF B THEN OUTPUT DRUGONLY;
ELSE OUTPUT WHY;
RUN;

*** READ IN RESULTS FROM "AFTER ERROR" OUTOACT ***;
DATA READIN;
INFILE FNL_DATA;
INPUT /*2013 UPDATED INPUTS TO ADJUST FOR UTILNUM*/
@ 1    PMROID   $13.
@ 14   BN       $60.
@ 74   PMFORMMC  ??
@ 82   STRNNUM  ??
@ 90   STRNUNIT  ??
@ 99   UTILNUM  $4.
@ 103  AMTNUM   ??
@ 109  AMTUNIT   ??
@ 111  SUPPNUM   ??
@ 114  TABNUM   ??
@ 161  IMPDF  $10.
@ 171  IMPSTNG $10.
@ 181  IMAMTNUM $10.
@ 191  THERCC  $3.
@ 194  OTCLEG  $1.
@ 195  AWP      12.
@ 207  EVPRICE  12.
@ 219  CODE     1.;

/*PMROID $ 1-13
BN $ 14-73
PMFORM  74-81
STRNNUM  82-89
STRNUNIT  90-97
UTILNUM $ 98-101
AMTNUM   102-106
AMTUNIT   107-109
SUPPNUM  110-112
TABNUM   113-116
IMPDF  $ 121-130
IMPSTNG $ 131-140
IMAMTNUM $ 141-150
THERCC  $ 151-153
OTCLEG  $  154-154
AWP      155-166
EVPRICE  167-178
CODE     179-179;*/


RUN;



DATA READIN;
*SET READINA READINFA READINFB READING READINK READINP READINT;
SET READIN;

ID=PMROID||UTILNUM;
** CORRECT THOSE DRUGS WHERE BB PUTS AN IMPUTED FORM;
** BUT WE DEEM THE REPORTED FORM TO BE RIGHT;
IF BN='ACETAMINOPHEN W/CODEINE'     AND PMFORMMC='1' THEN DO; PMFORM3='1 '; END;
IF BN='ACETASOL'                    AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='ACHROMYCIN'                  AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='ACTIFED W/CODEINE'           AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='ALBUTEROL'                   AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='ALBUTEROL'                   AND PMFORMMC='6' THEN DO; PMFORM3='6'; END;
IF BN='ALPRAZOLAM'                  AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='AZATHIOPRINE'                AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='BETAMETH'                    AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='BETAMETHASONE'               AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='BETAMETHASONE II'            AND PMFORMMC='6' THEN DO; PMFORM3='6'; END;
IF BN='BETAMETHASONE VAL'           AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='BETAMETHASONE VALERATE'      AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='BRONKODYL'                   AND PMFORMMC='6' THEN DO; PMFORM3='6'; END;
IF BN='CATAPRES'                    AND PMFORMMC='10' THEN DO; PMFORM3='10'; END;
IF BN='CETAPRED'                    AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='CHLORPROMAZINE HCL'          AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='CLINDAMYCIN'                 AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='CLONIDINE HCL'               AND PMFORMMC='10' THEN DO; PMFORM3='10'; END;
IF BN='CODEINE'                     AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='COLYTE'                      AND PMFORMMC='12' THEN DO; PMFORM3='12'; END;
IF BN='CONJUGATED ESTROGENS'        AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='CORTATRIGEN'                 AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='DDAVP'                       AND PMFORMMC='6' THEN DO; PMFORM3='6'; END;
IF BN='DEXAMETHASONE SOD PHOS'      AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='DOMEBORO'                    AND PMFORMMC='12' THEN DO; PMFORM3='12'; END;
IF BN='DUOFILM'                     AND PMFORMMC='4' THEN DO; PMFORM3='2'; END;
IF BN='DURA-VENT'                   AND PMFORMMC='6' THEN DO; PMFORM3='6'; END;
IF BN='ERYTHRO-RX'                  AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='ERYTHROMYCIN'                AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='ESTRADIOL'                   AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='ESTROGENS'                   AND PMFORMMC='10' THEN DO; PMFORM3='10'; END;
IF BN='FLUOCINOLONE ACETONIDE'      AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='FLUOROURACIL'                AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='FUROMIDE'                    AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='GENTAK'                      AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='GENTAMICIN SULFATE'          AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='GOLYTELY'                    AND PMFORMMC='12' THEN DO; PMFORM3='12'; END;
IF BN='GORDOCHOM'                   AND PMFORMMC='2' THEN DO; PMFORM3='2'; END;
IF BN='HALOPERIDOL'                 AND PMFORMMC='2' THEN DO; PMFORM3='2'; END;
IF BN='HYDROCODONE'                 AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='HYDROCODONE BITRATRATE'      AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='HYDROMORPHONE HCL'           AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='INHALENTS'                   AND PMFORMMC='6' THEN DO; PMFORM3='6'; END;
IF BN='KCL'                         AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='LUPRON DEPOT'                AND PMFORMMC='8' THEN DO; PMFORM3='8'; END;
IF BN='MACRODANTIN'                 AND PMFORMMC='2' THEN DO; PMFORM3='2'; END;
IF BN='MEPERIDINE HCL'              AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='METAPROTERENOL'              AND PMFORMMC='6' THEN DO; PMFORM3='6'; END;
IF BN='METHADONE'                   AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='METRONIDAZOLE'               AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='MONISTAT'                    AND PMFORMMC='5' THEN DO; PMFORM3='5'; END;
IF BN='MORPHINE SULFATE'            AND PMFORMMC='5' THEN DO; PMFORM3='5'; END;
IF BN='MYCOSTATIN'                  AND PMFORMMC='5' THEN DO; PMFORM3='5'; END;
IF BN='NEMBUTAL'                    AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='NEO/POLYMIXIN/HC'            AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='NEOMYCIN/POLY/HC'            AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='NITRO'                       AND PMFORMMC='10' THEN DO; PMFORM3='10'; END;
IF BN='NITRO-BID'                   AND PMFORMMC='10' THEN DO; PMFORM3='10'; END;
IF BN='NITROL'                      AND PMFORMMC='10' THEN DO; PMFORM3='10'; END;
IF BN='NTG'                         AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='NULYTELY'                    AND PMFORMMC='12' THEN DO; PMFORM3='12'; END;
IF BN='NYSTATIN'                    AND PMFORMMC='5' THEN DO; PMFORM3='5'; END;
IF BN='OCTICAIR'                    AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='ORGANIDIN'                   AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='OTOCORT'                     AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='PEDIOTIC'                    AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='PHENAPHEN W/CODEINE'         AND PMFORMMC='2' THEN DO; PMFORM3='2'; END;
IF BN='PHENYTOIN'                   AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='PHENYTOIN SODIUM'            AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='PHISOHEX'                    AND PMFORMMC='7' THEN DO; PMFORM3='7'; END;
IF BN='POTASSIUM'                   AND PMFORMMC='2' THEN DO; PMFORM3='2'; END;
IF BN='PREDNISOLONE ACETATE'        AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='PREDNISOLONE SOD PH'         AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='PREMARIN'                    AND PMFORMMC='5' THEN DO; PMFORM3='5'; END;
IF BN='PROCAINE'                    AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='PROCHLORPERAZIN/ISOP'        AND PMFORMMC='5' THEN DO; PMFORM3='5'; END;
IF BN='PROCTOFOAM-HC'               AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='PROGESTERONE'                AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='PROGESTERONE'                AND PMFORMMC='5' THEN DO; PMFORM3='5'; END;
IF BN='PROPRANOLOL HCL'             AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='REFAMPIN'                    AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='ROXANOL'                     AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='SODIUM POLYSTYRENE SULFATE'  AND PMFORMMC='2' THEN DO; PMFORM3='2'; END;
IF BN='SUCRALFATE'                  AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='SULFA'                       AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='SULFAMETHOPRIM'              AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='SULFAMETHOXAZOLE W/TMP'      AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='SULTRIN'                     AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='TALWIN'                      AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='TESTOSTERONE'                AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='TIMOLOL MALEATE'             AND PMFORMMC='3' THEN DO; PMFORM3='3'; END;
IF BN='TRIAMCINOLONE ACETONIDE'     AND PMFORMMC='4' THEN DO; PMFORM3='4'; END;
IF BN='TRIMETH'                     AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;
IF BN='TYPHOID VACCINE'             AND PMFORMMC='1' THEN DO; PMFORM3='8'; END;
IF BN='YOHIMBINE HCL'               AND PMFORMMC='1' THEN DO; PMFORM3='1'; END;

RUN;

PROC SORT DATA=READIN NODUPKEY; BY ID;RUN;

*** MERGE TO GET ALL DRUGS AND KEEP THOSE THAT DIDN'T GO THRU BDMS PROCESS;

DATA MCBSDATA.OUTCOMM_Y&CurrYear;
MERGE DRUGONLY (IN=A) 
      READIN ;
BY ID;
IF A;
*** DROP ALL OTCS *** ;
* IF OTCLEG='O' THEN DELETE; /* DO THIS AFTER TREIM IS ASSIGNED */
*** CHANGE OTHER FORMS WHERE NECESSARY ***;
IF IMPDF='AEROSOL' THEN PMFORMMC='6';
IF IMPDF='JELLIES' THEN PMFORMMC='4';
IF IMPDF='LIQUIDS' THEN PMFORMMC='2';
IF IMPDF='OTHERS' THEN PMFORMMC='91';
IF IMPDF='PATCHES' THEN PMFORMMC='10';
IF IMPDF='PILLS' THEN PMFORMMC='1';
IF IMPDF='POWDER' THEN PMFORMMC='12';
IF IMPDF='CREAM' THEN PMFORMMC='4';
IF IMPDF='DROPS' THEN PMFORMMC='3';
IF IMPDF='INJECTABLE' THEN PMFORMMC='8';
IF IMPDF='SHAMPOO' THEN PMFORMMC='7';
IF IMPDF='SUPPOS.' THEN PMFORMMC='5';
** ELIMINATE EVPRICES WHERE FORM WAS IMPUTED WRONGLY **;
IF PMFORM3 NE '' THEN DO; PMFORMMC=PMFORM3; EVPRICE=.; OOPS=1; END;
** ELIMINATE EVPRICES WHERE MILLILITERS AWPS WERE VERY TINY **;
IF AMTUNIT='5' AND EVPRICE<1 THEN EVPRICE=.;
 
** SET MINIMUM EVPRICE OF .50 **;
IF EVPRICE NE . AND EVPRICE < .50 THEN EVPRICE =.50;
RUN;


TITLE 'HOW MANY EVPRICES WERE TURNED OFF?';
PROC FREQ DATA = MCBSDATA.OUTCOMM_Y&CurrYear;  
TABLES OOPS/MISSING; 
RUN;TITLE;
 
TITLE ' OTC-LEG';
PROC FREQ DATA = MCBSDATA.OUTCOMM_Y&CurrYear; 
TABLES OTCLEG; 
RUN;TITLE;

TITLE 'SHOULD BE NO ND-NONDRUGS';
PROC FREQ DATA = MCBSDATA.OUTCOMM_Y&CurrYear; ; 
TABLES BN; 
RUN;TITLE;

PROC PRINT DATA = MCBSDATA.OUTCOMM_Y&CurrYear (OBS=200); 
WHERE OOPS=1; 
RUN;

ods rtf close;
