*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
|      PROGRAM: 07_RETAIL                                                               |
|      UPDATED: 01/21/2011                                                              |
|  INPUT FILES: MCBSDATA.FINAL_&CURRYEAR._V2, FINAL_DATA.txt                            |
| OUTPUT FILES: None. Print (RTF) output only                                           |
|  DESCRIPTION: Legacy Description: "THIS CODE DEVELOPS OUR PAYOR FACTOR FOR RETAIL     |
|               BUT ONLY LOOKS AT THE ONE TO ONE RECORDS FROM WESTAT"                   |
|                                                                                       |
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*;
ODS HTML CLOSE;
  ODS HTML;

OPTION MLOGIC MPRINT SYMBOLGEN COMPRESS=YES;
options nofmterr;

%LET CURRYEAR=20;
%LET LASTYEAR=19;

%let location = C:\Users\S1C3\RIC PME\MCBS\20&CURRYEAR.\PME\Data\;

libname MCBSDATA  "&location";
filename THRUBDMS "&location.THRUBDMS.txt";
filename FNL_DATA "&location.FINAL_DATA.txt";

ods rtf bodytitle file ="&location.Output\07_RETAIL Output - %sysfunc(DATE(),mmddyyd10.).rtf";


DATA TOTALCH;
LENGTH EVNTNUM $3.;
SET MCBSDATA.FINAL_&CURRYEAR._V2
    (KEEP=BASEID EVNTNUM ROUND TOTALCHG PMEDNAME _PURCHPM
          NUMLINKS  _SOPCARE _SOPCAID _SOPPRVE _SOPPRVI _SOPOOP _SOPOTH COSTNUM
          NUMSAME _SOPDISC _SOPVA _SOPPHMO _SOPPD _SOPMA _NEWRECS _DIFPMS _RECSPM UTILNUM );

ID=BASEID||EVNTNUM||ROUND||UTILNUM;
RUN;
PROC SORT DATA=TOTALCH NODUPKEY;
BY ID;
RUN;

***** GET RESULTS OF THRUBDMS ****;
DATA pmformmc;
INFILE FNL_DATA; 
/*2013 UPDATED INPUTS TO ADJUST FOR UTILNUM*/
/*2015 updated inputs*/
INPUT 
@ 1    PMROID   $13.
@ 14   BN       $60.
@ 74   pmformmc  ??
@ 82   STRNNUM  ??
@ 90   STRNUNIT  ??
@ 99   UTILNUM  $4.
@ 103  AMTNUM   ??
@ 109  AMTUNIT   ??
@ 111  SUPPNUM   ??
@ 114  TABNUM   ??
@ 161  IMPDF  $10.
@ 171  IMPSTNG $10.
@ 181  IMAMTNUM $10.
@ 191  THERCC  $3.
@ 194  OTCLEG  $1.
@ 195  AWP      12.
@ 207  EVPRICE  12.
@ 219  CODE     1.;
/*
PMROID $ 1-13
BN $ 14-43
pmformmc $ 44-46
STRNNUM  47-54
STRNUNIT $ 55-57
UTILNUM $ 58-61
AMTNUM   62-69
AMTUNIT  $ 70-72
SUPPNUM  73-75
TABNUM   76-79
IMPDF  $ 121-130
IMPSTNG $ 131-140
IMAMTNUM $ 141-150
THERCC  $ 151-153
OTCLEG  $  154-154
AWP      155-165
EVPRICE  167-177
CODE     179-179;*/

RUN;


DATA PMFORMFX;
SET pmformmc;
 
IF OTCLEG='O' THEN DELETE;
ID=PMROID||UTILNUM;
 
*** SOME FORMS WERE IMPROPERLY SET TO OTHER FORMS ***;
* WE WILL SET THEM BACK HERE;
IF BN='ACETAMINOPHEN W/CODEINE'     AND pmformmc='1' THEN DO; PMFORM3='1 '; END;
IF BN='ACETASOL'                    AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='ACHROMYCIN'                  AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='ACTIFED W/CODEINE'           AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='ALBUTEROL'                   AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='ALBUTEROL'                   AND pmformmc='6' THEN DO; PMFORM3='6'; END;
IF BN='ALPRAZOLAM'                  AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='AZATHIOPRINE'                AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='BETAMETH'                    AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='BETAMETHASONE'               AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='BETAMETHASONE II'            AND pmformmc='6' THEN DO; PMFORM3='6'; END;
IF BN='BETAMETHASONE VAL'           AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='BETAMETHASONE VALERATE'      AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='BRONKODYL'                   AND pmformmc='6' THEN DO; PMFORM3='6'; END;
IF BN='CATAPRES'                    AND pmformmc='10' THEN DO; PMFORM3='10'; END;
IF BN='CETAPRED'                    AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='CHLORPROMAZINE HCL'          AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='CLINDAMYCIN'                 AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='CLONIDINE HCL'               AND pmformmc='10' THEN DO; PMFORM3='10'; END;
IF BN='CODEINE'                     AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='COLYTE'                      AND pmformmc='12' THEN DO; PMFORM3='12'; END;
IF BN='CONJUGATED ESTROGENS'        AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='CORTATRIGEN'                 AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='DDAVP'                       AND pmformmc='6' THEN DO; PMFORM3='6'; END;
IF BN='DEXAMETHASONE SOD PHOS'      AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='DOMEBORO'                    AND pmformmc='12' THEN DO; PMFORM3='12'; END;
IF BN='DUOFILM'                     AND pmformmc='4' THEN DO; PMFORM3='2'; END;
IF BN='DURA-VENT'                   AND pmformmc='6' THEN DO; PMFORM3='6'; END;
IF BN='ERYTHRO-RX'                  AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='ERYTHROMYCIN'                AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='ESTRADIOL'                   AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='ESTROGENS'                   AND pmformmc='10' THEN DO; PMFORM3='10'; END;
IF BN='FLUOCINOLONE ACETONIDE'      AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='FLUOROURACIL'                AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='FUROMIDE'                    AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='GENTAK'                      AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='GENTAMICIN SULFATE'          AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='GOLYTELY'                    AND pmformmc='12' THEN DO; PMFORM3='12'; END;
IF BN='GORDOCHOM'                   AND pmformmc='2' THEN DO; PMFORM3='2'; END;
IF BN='HALOPERIDOL'                 AND pmformmc='2' THEN DO; PMFORM3='2'; END;
IF BN='HYDROCODONE'                 AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='HYDROCODONE BITRATRATE'      AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='HYDROMORPHONE HCL'           AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='INHALENTS'                   AND pmformmc='6' THEN DO; PMFORM3='6'; END;
IF BN='KCL'                         AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='LUPRON DEPOT'                AND pmformmc='8' THEN DO; PMFORM3='8'; END;
IF BN='MACRODANTIN'                 AND pmformmc='2' THEN DO; PMFORM3='2'; END;
IF BN='MEPERIDINE HCL'              AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='METAPROTERENOL'              AND pmformmc='6' THEN DO; PMFORM3='6'; END;
IF BN='METHADONE'                   AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='METRONIDAZOLE'               AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='MONISTAT'                    AND pmformmc='5' THEN DO; PMFORM3='5'; END;
IF BN='MORPHINE SULFATE'            AND pmformmc='5' THEN DO; PMFORM3='5'; END;
IF BN='MYCOSTATIN'                  AND pmformmc='5' THEN DO; PMFORM3='5'; END;
IF BN='NEMBUTAL'                    AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='NEO/POLYMIXIN/HC'            AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='NEOMYCIN/POLY/HC'            AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='NITRO'                       AND pmformmc='10' THEN DO; PMFORM3='10'; END;
IF BN='NITRO-BID'                   AND pmformmc='10' THEN DO; PMFORM3='10'; END;
IF BN='NITROL'                      AND pmformmc='10' THEN DO; PMFORM3='10'; END;
IF BN='NTG'                         AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='NULYTELY'                    AND pmformmc='12' THEN DO; PMFORM3='12'; END;
IF BN='NYSTATIN'                    AND pmformmc='5' THEN DO; PMFORM3='5'; END;
IF BN='OCTICAIR'                    AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='ORGANIDIN'                   AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='OTOCORT'                     AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='PEDIOTIC'                    AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='PHENAPHEN W/CODEINE'         AND pmformmc='2' THEN DO; PMFORM3='2'; END;
IF BN='PHENYTOIN'                   AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='PHENYTOIN SODIUM'            AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='PHISOHEX'                    AND pmformmc='7' THEN DO; PMFORM3='7'; END;
IF BN='POTASSIUM'                   AND pmformmc='2' THEN DO; PMFORM3='2'; END;
IF BN='PREDNISOLONE ACETATE'        AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='PREDNISOLONE SOD PH'         AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='PREMARIN'                    AND pmformmc='5' THEN DO; PMFORM3='5'; END;
IF BN='PROCAINE'                    AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='PROCHLORPERAZIN/ISOP'        AND pmformmc='5' THEN DO; PMFORM3='5'; END;
IF BN='PROCTOFOAM-HC'               AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='PROGESTERONE'                AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='PROGESTERONE'                AND pmformmc='5' THEN DO; PMFORM3='5'; END;
IF BN='PROPRANOLOL HCL'             AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='REFAMPIN'                    AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='ROXANOL'                     AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='SODIUM POLYSTYRENE SULFATE'  AND pmformmc='2' THEN DO; PMFORM3='2'; END;
IF BN='SUCRALFATE'                  AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='SULFA'                       AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='SULFAMETHOPRIM'              AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='SULFAMETHOXAZOLE W/TMP'      AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='SULTRIN'                     AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='TALWIN'                      AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='TESTOSTERONE'                AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='TIMOLOL MALEATE'             AND pmformmc='3' THEN DO; PMFORM3='3'; END;
IF BN='TRIAMCINOLONE ACETONIDE'     AND pmformmc='4' THEN DO; PMFORM3='4'; END;
IF BN='TRIMETH'                     AND pmformmc='1' THEN DO; PMFORM3='1'; END;
IF BN='TYPHOID VACCINE'             AND pmformmc='1' THEN DO; PMFORM3='8'; END;
IF BN='YOHIMBINE HCL'               AND pmformmc='1' THEN DO; PMFORM3='1'; END;


RUN;

DATA PMFORMFX;
SET PMFORMFX;
IF PMFORM3>'0' THEN EVPRICE=.;
IF AMTUNIT= 5 AND EVPRICE<1 THEN EVPRICE=.;
IF EVPRICE<.5 AND EVPRICE NE . THEN EVPRICE=.5;
RUN;

PROC SORT DATA=PMFORMFX; BY ID; RUN;

DATA TOG;
MERGE TOTALCH (IN=A) 
      PMFORMFX (IN=B);
BY ID;
IF A AND B;
*IF TOTALCHG NE -8.00;
IF ROUND='10' THEN DELETE;
RUN;

DATA RETAIL;
SET TOG;
*IF TOTALCHG>0 AND EVPRICE NE .;
 
IF (_SOPCAID=0 AND _SOPCARE=0 AND _SOPPHMO=0 AND _SOPPD=0 AND _SOPMA=0 AND _SOPOTH=0 AND _SOPPRVE=0 AND _SOPPRVI=0 AND _SOPVA=0 AND _SOPOOP=1 AND _SOPDISC=0)
OR (_SOPCAID=0 AND _SOPCARE=0 AND _SOPPHMO=0 AND _SOPPD=0 AND _SOPMA=0 AND _SOPOTH=0 AND _SOPPRVE=1 AND _SOPPRVI=0 AND _SOPVA=0 AND _SOPOOP=0 AND _SOPDISC=0)
OR (_SOPCAID=0 AND _SOPCARE=0 AND _SOPPHMO=0 AND _SOPPD=0 AND _SOPMA=0 AND _SOPOTH=0 AND _SOPPRVE=1 AND _SOPPRVI=0 AND _SOPVA=0 AND _SOPOOP=0 AND _SOPDISC=1)
OR (_SOPCAID=0 AND _SOPCARE=0 AND _SOPPHMO=0 AND _SOPPD=0 AND _SOPMA=0 AND _SOPOTH=0 AND _SOPPRVE=0 AND _SOPPRVI=1 AND _SOPVA=0 AND _SOPOOP=0 AND _SOPDISC=0)
OR (_SOPCAID=0 AND _SOPCARE=0 AND _SOPPHMO=0 AND _SOPPD=0 AND _SOPMA=0 AND _SOPOTH=0 AND _SOPPRVE=1 AND _SOPPRVI=1 AND _SOPVA=0 AND _SOPOOP=0 AND _SOPDISC=0)
OR (_SOPCAID=0 AND _SOPCARE=0 AND _SOPPHMO=0 AND _SOPPD=0 AND _SOPMA=0 AND _SOPOTH=0 AND _SOPPRVE=0 AND _SOPPRVI=0 AND _SOPVA=0 AND _SOPOOP=1 AND _SOPDISC=1)
OR (_SOPCAID=0 AND _SOPCARE=0 AND _SOPPHMO=0 AND _SOPPD=0 AND _SOPMA=0 AND _SOPOTH=0 AND _SOPPRVE=1 AND _SOPPRVI=0 AND _SOPVA=0 AND _SOPOOP=1 AND _SOPDISC=0)
OR (_SOPCAID=0 AND _SOPCARE=0 AND _SOPPHMO=0 AND _SOPPD=0 AND _SOPMA=0 AND _SOPOTH=0 AND _SOPPRVE=1 AND _SOPPRVI=0 AND _SOPVA=0 AND _SOPOOP=1 AND _SOPDISC=1)
OR (_SOPCAID=0 AND _SOPCARE=0 AND _SOPPHMO=0 AND _SOPPD=0 AND _SOPMA=0 AND _SOPOTH=0 AND _SOPPRVE=0 AND _SOPPRVI=1 AND _SOPVA=0 AND _SOPOOP=1 AND _SOPDISC=0);

RUN;

*TO ARRIVE AT OUR FACTOR, WE FIRST LIMITED THOSE TO WHERE
*THE NUMBER OF COSTS ASSOC. WITH THE TOTALCHG WAS 1 AND
*WE TOOK OUT THE OUTLIERS FOR BOTH TOTALCHG AND EVPRICE;
DATA SINGLE;
SET RETAIL ;
IF _PURCHPM=1 AND _DIFPMS=1 AND _RECSPM=1 AND _NEWRECS=1 then output single;
else IF AMTUNIT=5 AND EVPRICE<1 THEN DELETE;
run;


DATA PILLPAT;
SET SINGLE;
IF pmformmc=1 OR pmformmc=10;
IF IMPDF=' ' and IMPSTNG=' ';
RUN;
DATA SUPP;
SET SINGLE;
IF pmformmc=5;
IF IMPDF=' ' and IMPSTNG=' ';
RUN;
DATA OTHERS;
SET SINGLE;
IF pmformmc NE 1 AND pmformmc NE 5 AND pmformmc NE 10;
IF IMPDF=' ' and IMAMTNUM=' ' and IMPSTNG=' ';
RUN;
DATA SINGLE;
SET PILLPAT SUPP OTHERS;
RUN;
DATA CHEAP;
SET SINGLE;
IF EVPRICE<5 ;
RUN;
DATA MODERATE;
SET SINGLE;
IF EVPRICE>4.99 AND EVPRICE<20;
RUN;

DATA EXPENSIV;
SET SINGLE;
IF EVPRICE>19.99;
RUN;


PROC MEANS DATA=CHEAP NOPRINT;
VAR TOTALCHG EVPRICE;
OUTPUT OUT =MEANS_CHEAP 
 mean(totalchg)=totalchg_mean
 mean(EVPRICE)=EVPRICE_mean;
RUN;

PROC MEANS DATA=MODERATE NOPRINT;
VAR TOTALCHG EVPRICE;
OUTPUT OUT =MEANS_MODERATE 
 mean(totalchg)=totalchg_mean
 mean(EVPRICE)=EVPRICE_mean;
RUN;

PROC MEANS DATA=EXPENSIV NOPRINT;
VAR TOTALCHG EVPRICE;
OUTPUT OUT =MEANS_EXPENSIV 
 mean(totalchg)=totalchg_mean
 mean(EVPRICE)=EVPRICE_mean;
RUN;

data means_RETAIL;
set 
MEANS_CHEAP (in=a)
MEANS_MODERATE (in=b)
MEANS_EXPENSIV (in=c) ;
if A then type="R_LT5 ";
if B then type="R_5_20";
if C then type="R_GT20";
factor=totalchg_mean/EVPRICE_mean;
run;


title1 'RETAIL (SINGLE)';
PROC UNIVARIATE DATA=CHEAP   ;
VAR TOTALCHG EVPRICE;
TITLE2 'AVGS FOR EVPRICE <5';
RUN;
PROC UNIVARIATE DATA=MODERATE;
VAR TOTALCHG EVPRICE;
TITLE2 'AVGS FOR EVPRICE 5-19.99';
RUN;
PROC UNIVARIATE DATA=EXPENSIV;
VAR TOTALCHG EVPRICE;
TITLE2 'AVGS FOR EVPRICE>19.99';
RUN;title1;title2;

 
*TO ARRIVE AT OUR FACTOR, WE SECOND LIMITED THOSE TO WHERE
*THE NUMBER OF COSTS ASSOC. WITH THE TOTALCHG WAS>1 AND
*WE TOOK OUT THE OUTLIERS FOR BOTH TOTALCHG AND EVPRICE;
DATA MULTIPLE;
SET RETAIL ;
IF _PURCHPM>1 AND _DIFPMS=1 AND _RECSPM=1 AND _NEWRECS=1;
IF NUMSAME < 0 AND NUMLINKS < 0 THEN DELETE;
IF NUMSAME < 0 THEN TOTALCH2=TOTALCHG/NUMLINKS;
IF NUMSAME > 0 THEN TOTALCH2=TOTALCHG;
IF AMTUNIT=5 AND EVPRICE<1 THEN DELETE;
RUN;
PROC SORT DATA=MULTIPLE OUT=LINKSUM(KEEP=NUMLINKS NUMSAME);
BY NUMLINKS NUMSAME;
RUN;

PROC FREQ DATA=LINKSUM;
TABLES NUMLINKS*NUMSAME;
TITLE 'SHOULD BE NONE WITH DOUBLE NEGATIVE';
RUN; TITLE;

DATA PILLPAT;
SET MULTIPLE;
IF pmformmc=1 OR pmformmc=10;
IF IMPDF=' ' and IMPSTNG=' ';
RUN;
DATA SUPP;
SET MULTIPLE;
IF pmformmc=5;
IF IMPDF=' ' and IMPSTNG=' ';
RUN;
DATA OTHERS;
SET MULTIPLE;
IF pmformmc NE 1 AND pmformmc NE 5 AND pmformmc NE 10;
IF IMPDF=' ' and IMAMTNUM=' ' and IMPSTNG=' ';
RUN;
DATA MULTIPLE;
SET PILLPAT SUPP OTHERS;
RUN;
DATA CHEAPM;
SET MULTIPLE;
IF EVPRICE<5 ;
RUN;
DATA MODERATM;
SET MULTIPLE;
IF EVPRICE>4.99 AND EVPRICE<20;
RUN;
DATA EXPENSIM;
SET MULTIPLE;
IF EVPRICE>19.99;
RUN;

PROC MEANS DATA=CHEAPM NOPRINT;
VAR TOTALCHG EVPRICE;
OUTPUT OUT =MEANS_CHEAPM 
 mean(totalchg)=totalchg_mean
 mean(EVPRICE)=EVPRICE_mean;
RUN;

PROC MEANS DATA=MODERATM NOPRINT;
VAR TOTALCHG EVPRICE;
OUTPUT OUT =MEANS_MODERATM 
 mean(totalchg)=totalchg_mean
 mean(EVPRICE)=EVPRICE_mean;
RUN;

PROC MEANS DATA=EXPENSIM NOPRINT;
VAR TOTALCHG EVPRICE;
OUTPUT OUT =MEANS_EXPENSIM 
 mean(totalchg)=totalchg_mean
 mean(EVPRICE)=EVPRICE_mean;
RUN;

data means_allM;
set 
MEANS_CHEAPM (in=a)
MEANS_MODERATM (in=b)
MEANS_EXPENSIM (in=c) ;
if A then type="R_LT5 ";
if B then type="R_5_20";
if C then type="R_GT20";
factor=totalchg_mean/EVPRICE_mean;
run;


title1 'RETAIL (MULTIPLE)';

PROC UNIVARIATE DATA=CHEAPM  ;
VAR TOTALCH2 EVPRICE;
TITLE2 'AVGS FOR EVPRICE <5 MULT';
RUN;
PROC UNIVARIATE DATA=MODERATM;
VAR TOTALCH2 EVPRICE;
TITLE2 'AVGS FOR EVPRICE 5-19.99 MULT';
RUN;
PROC UNIVARIATE DATA=EXPENSIM;
VAR TOTALCH2 EVPRICE;
TITLE2 'AVGS FOR EVPRICE>19.99 MULT';
RUN;TITLE1;TITLE2;


DATA ALLCHEAP;
SET CHEAP CHEAPM;
IF TOTALCH2 NE . THEN TOTALCHG=TOTALCH2;
RUN;
DATA ALLMOD;
SET MODERATE MODERATM;
IF TOTALCH2 NE . THEN TOTALCHG=TOTALCH2;
RUN;
DATA ALLEXP;
SET EXPENSIV EXPENSIM;
IF TOTALCH2 NE . THEN TOTALCHG=TOTALCH2;
RUN;


PROC MEANS DATA=ALLCHEAP NOPRINT;
VAR TOTALCHG EVPRICE;
OUTPUT OUT =MEANS_ALLCHEAP 
 mean(totalchg)=totalchg_mean
 mean(EVPRICE)=EVPRICE_mean;
RUN;

PROC MEANS DATA=ALLMOD NOPRINT;
VAR TOTALCHG EVPRICE;
OUTPUT OUT =MEANS_ALLMOD 
 mean(totalchg)=totalchg_mean
 mean(EVPRICE)=EVPRICE_mean;
RUN;

PROC MEANS DATA=ALLEXP NOPRINT;
VAR TOTALCHG EVPRICE;
OUTPUT OUT =MEANS_ALLEXP 
 mean(totalchg)=totalchg_mean
 mean(EVPRICE)=EVPRICE_mean;
RUN;

data means_all;
set 
MEANS_ALLCHEAP (in=a)
MEANS_ALLMOD (in=b)
MEANS_ALLEXP (in=c) ;
if A then type="R_LT5 ";
if B then type="R_5_20";
if C then type="R_GT20";
factor=totalchg_mean/EVPRICE_mean;
run;


title1 'RETAIL (ALL)';
PROC UNIVARIATE DATA=ALLCHEAP;
VAR TOTALCHG EVPRICE;
TITLE2 'AVGS FOR EVPRICE<5 ALL';
RUN;
PROC UNIVARIATE DATA=ALLMOD;
VAR TOTALCHG EVPRICE;
TITLE2 'AVGS FOR EVPRICE5-19.99 ALL';
RUN;
PROC UNIVARIATE DATA=ALLEXP;
VAR TOTALCHG EVPRICE;
TITLE2 'AVGS FOR EVPRICE5>19.99 ALL';
RUN;TITLE1;TITLE2;


DATA EVERY;
SET ALLCHEAP ALLMOD ALLEXP;
RUN;


PROC UNIVARIATE DATA=EVERY;
VAR TOTALCHG EVPRICE;
TITLE 'HOW MUCH DID TOTAL CHARGE AND AWP GO UP FROM LAST YEAR';
TITLE2 '  YOU WILL HAVE TO RUN LAST YEARS TO FIND OUT';
RUN;TITLE;TITLE2;
ODS RTF CLOSE;

ods rtf bodytitle file ="&location.Output\Retail (All) Factors - %sysfunc(DATE(),mmddyyd10.).rtf";
proc sql;
TITLE "FACTORS FOR RETAIL (ALL)";
select type, factor, totalchg_mean, EVPRICE_mean from means_all;
quit;TITLE;
ODS RTF CLOSE;
