*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
|      PROGRAM: 10_SOB                                                                  |
|      UPDATED: 10/05/2012 (replaced HMO with pHMO and in all SOB macro files)          |
|  INPUT FILES: SOB: 100 200,300,400,450,500,CARE,MISS,OTH,REST                         |
| OUTPUT FILES: TOWESTAT_&CURRYEAR                                                      |
|  DESCRIPTION: Legacy program that makes several final adjustments and creates         |
|                ToWestat file                                                          |
|                                                                                       |
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*;
OPTION MLOGIC MPRINT SYMBOLGEN COMPRESS=YES;
ods html close;
ods html;

options nofmterr;

%LET CURRYEAR=20;
%LET LASTYEAR=19;
%let unused = pm_events_impd_89_2021; ***NEED TO UPDATE YEARLY (use last round -- add 3 to round and next year);


*** Discount Factors *****;
%let R_factor_LT5  = .;*UPDATED 4/19/22; 
%let R_factor_5_20 = .;*UPDATED 4/19/22;
%let R_factor_GT20 = .;*UPDATED 4/19/22;
%let P_factor      =0.971;*UPDATED 4/19/22; 
%let A_factor      =0.971;*UPDATED 4/19/22;

/*Factors below should remain the same for the 2013 file -- talked with Chris and Luping*/
**Factors below were updated 04/29/2015 to represent WAC-- old factors were multiplied by 1.8;
%let E_factor      =1.044; /*0.58;*/
%let H_factor      =1.512; /*0.84;*/
%let V_factor      =0.972; /*0.54;*/
%let C_factor      =1.53; %LET C_PLUS=4.77;  /*0.85; %LET C_PLUS=4.77;*/
%let O_factor      =1.62; %LET O_PLUS=3.50; /*0.90; %LET O_PLUS=3.50;*/
%let M_factor      =2.25; /*1.25;*/



%let location = C:\Users\S1C3\RIC PME\MCBS\20&CURRYEAR.\PME\Data\;
%let loc_last = C:\Users\S1C3\RIC PME\MCBS\20&LASTYEAR.\PME\Data\;
%LET MACRO_LOC = C:\Users\S1C3\RIC PME\MCBS\20&CURRYEAR.\PME\SAS Code 20&CURRYEAR.\Macros;



libname  MCBSDATA "&location";
LIBNAME  MCBSLAST "&loc_last";
FILENAME INCLIB   "&MACRO_LOC";

%put STARTED ON %sysfunc(DATE(),mmddyyd10.) AT: %sysfunc(TIME(),timeampm8.);

%INC INCLIB(
M09_SOB100
M09_SOB200
M09_SOB300
M09_SOB400
M09_SOB450
M09_SOB500
M09_SOB700
M09_SOBCARE
M09_SOBMISS
M09_SOBREST
) / source2; *note option "/source2" writes included code to the SAS log;

FILENAME INCLIB CLEAR;



*** GET NEW VARS FOR CURRENT YEAR;
DATA NEWVARS
	(KEEP=ID INS_FLGS RX_FLGS HDPHMO HDOPUB HDPRVE HDPRVI HDRX XTRAS EV95FLG PMSUMFLG);

LENGTH EVNTNUM $3.;

set MCBSDATA.FINAL_&CURRYEAR._V2;
ID = BASEID||EVNTNUM||ROUND||UTILNUM;
RUN;

PROC SORT DATA=NEWVARS NODUPKEY; BY ID; RUN;


DATA ALLSOB;
SET
MCBSDATA.SOB100
MCBSDATA.SOB200
MCBSDATA.SOB300
MCBSDATA.SOB400
MCBSDATA.SOB450
MCBSDATA.SOB500
MCBSDATA.SOBOTH
MCBSDATA.SOBCARE
MCBSDATA.SOBMISS
MCBSDATA.SOBREST
;
ID = BASEID||EVNTNUM||ROUND||UTILNUM;
RUN;
PROC SORT DATA=ALLSOB NODUPKEY dupout=all_dups; BY ID; RUN;



****** REMOVE LAST YEARS EVENTS THAT WERE CARRIED TO CALCULATE THE EVENT COST FOR UNUSED EVENTS
       (I.E., DROP EVENTS IN THE SAME COSTNUM THAT WERE USED LAST YEAR);
proc sql; 
create table ALL&curryear
as select 
a.*
from ALLSOB                       A
        left join 
     MCBSDATA.FINAL_&CURRYEAR._V2 B
       ON A.BASEID  = B.BASEID
	  AND A.ROUND   = B.ROUND
      AND A.EVNTNUM = B.EVNTNUM
      AND A.UTILNUM = B.UTILNUM   
WHERE B.UNUSED NE "DROP"
order by ID;
QUIT;



***Legacy Processing...;
DATA ALL&CurrYear mcbsdata.Deleted_OTC_&curryear;
MERGE ALL&CurrYear   (IN=A)
	  NEWVARS (IN=B);
BY ID;
IF A;

*** MAKE ADJUSTMENTS WHERE AMTS ARE TOO SMALL ***;
IF _TREIM  <-.002 THEN _TREIM=.;
IF _AMTCARE<-.002 THEN _AMTCARE=.;
IF _AMTCAID<-.002 THEN _AMTCAID=.;
IF _AMTpHMO <-.002 THEN _AMTpHMO=.;
IF _AMTVA  <-.002 THEN _AMTVA=.;
IF _AMTPRVE<-.002 THEN _AMTPRVE=.;
IF _AMTPRVI<-.002 THEN _AMTPRVI=.;
IF _AMTOOP <-.002 THEN _AMTOOP=.;
IF _AMTDISC<-.002 THEN _AMTDISC=.;
IF _AMTOTH <-.002 THEN _AMTOTH=.;

*** SET SOME OTCLEG'S TO O AND I ***;


IF PMEDNAME='A & D UNG-                    ' THEN DO; OTCLEG='O';END;
IF PMEDNAME='A & D VITAMIN                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='A DECONGESTANT                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='A&D UNG                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='A&D VITAMIN                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ABSORBINE JR                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ALPHA KERI                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ALPHA KERI BATH               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ALPHA KERI BATH OIL           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ALPHA-KERI                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ASA FREE                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ASPIRIN E.C. (S. ECOTRIN)     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ASPIRIN ENTERIC COATED        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ASPIRIN-BABY                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ASPIRIN-E.C.                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='AVEENO BATH OIL               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='AVEENO-SOAP-BATH              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='AVENO-SOAP-BATH               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='B COMPLEX VITA PLUS FOLIC     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='B COMPLEX VITAMIN PLUS        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='B COMPLEX VITAMINS            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='B COMPLEX WITH C              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='B 12 VITAMIN                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='B 12 VITAMINS AND NEEDLES     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='B-COMPLEX VIT PLUS            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='B/12                          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='BABY SHAMPOO                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='BASIS                         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='BASIS SOAP                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='BAYER BABY ASPRIN             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME="BAYER CHILDREN'S ASPIRIN      " THEN DO; OTCLEG='O'; END;
IF PMEDNAME="BAYER'S CHILDREN ASPIRIN      " THEN DO; OTCLEG='O'; END;
IF PMEDNAME="BAYER'S CHILDREN'S ASPIRIN    " THEN DO; OTCLEG='O'; END;
IF PMEDNAME="BAYER'S CHILDRENS ASPIRIN     " THEN DO; OTCLEG='O'; END;
IF PMEDNAME='BEN GAY                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='BEN GAY OINTMENT              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='BENGAY                        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='BLISTEX                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CALADRYL                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CALADRYL LOTION               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CALAMINE LOTION               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CALAMINE/CALADRYE             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CAMEO SOAP                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CAMPHO-PHENQUE                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CAMPHOPHENIQUE                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CENTRAL VITE                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CENTROBITE CENTRUM            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CENTROVITE JR                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CENTRUM JR WITH CALCIUM       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CENTRUM JR WITH EXTRA VITAMIN ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CENTRUM JR/CALCIUM            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CEPACOL                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CEPACOL LOZENGES              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CEPOCOL                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CHLOROSEPTIC SPRAY            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CITRATE MAGNESIA              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CITRATE OF MAGNE              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CITRATE OF MAGNESIA           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CITRISOURCE                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CLING WRAP DRESSING           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CO TYLENOL                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='COD LIVER OIL                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='COMPLETE                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CORNSTARCH                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='CRANBERRY JUICE               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='DAILY MULTIPLE VITAMINS       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='DAILY VITE                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='DAILY VITE MULTI VIT          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='DAILY-VITE                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='DESENEX                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='DESERT STORM SUN SCREEN       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='DIMETAME DC                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='DIPHEN BENADRYL               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='EXCEDRIN PM                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='EXT ST TYLENOL                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='EXTRA S. TYLENOL              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='EXTRA STRENGHT TYLENOL        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='EXTRA STRENGTH BUFFERIN       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='EXTRA STRENGTH TEYNELOL       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='EXTRA STRENGTH TYLENOL        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='EXTRA STRENGTH TYNEDOL        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='GATERAID                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='GATORADE FLUSHES              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='GLASSES                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='GRAPEFRUIT OR ORANGE JUICE    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='GREAT SHAKE                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='GREAT SHAKES                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='HEAD & SHOULDERS              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='HEALTH SHAKES                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='HEALTH SHAKLEY                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='HEART BURN MED.               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='HERBS                         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='HYDROGEN PEROXID              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='HYDROGEN PEROXIDE             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='HYDROGEN PEXROXIDE            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='I CAP VITAMINS                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='IBERET-500                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='IMMODIUM AD                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='IMODIAMAD                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='IMODIUM AD                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='IMODIUM-AD                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='IVERIT 500                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='J & J DRESSING                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='JOHNSON & JOHNSON BABY SHAMPOO' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='JOHNSON BABY SHAMPOO          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='JOHNSONS SHAMPOO              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='JUICE & CRACKERS              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='LAMBS WOOL                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='LESINEX                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='LISTERINE                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='M.O.M. W/CASCARA              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='M.O.M. WITH CASC              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='M.O.M. WITH CASCARA           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MAGIC MOUTH WASH              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MAGIC MOUTHWASH               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MAGIC MOUTHWASH #1            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MILK & COOKIES                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MILTIVITAMIN                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOM & CC                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOM CONCASCARA                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOM MILK OF MAGNESIA          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOM W/CASCARA                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOM W/5 CC CASCARA            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOM WITH CASCARA              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOM WITH CASDARA              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOUTH SORE                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOUTH ULCER SALVE             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MOUTH WASH                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MTV WITH MINERALS             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULIT VITIAMIN                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI BRET FOLIC 500          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VI                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VIT                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VIT TABS                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VIT W/IRON              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VIT W/MINERAL           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VIT. IRON               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN & IRON          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN & MINERAL       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN W/IRON          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN W/MINERAL       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN W/MINERALS      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN WITH IRON       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN WITH MI         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN WITH MINERALS   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN-IRON            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN/IRON            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMIN/W IRON          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMINS                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITAMINS WITH MINERALS  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITE                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITIME                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITIMIN                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI VITIMIN W/IRON          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI. VITAMIN                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VIT IRON                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VIT ZINC                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VIT. W/MINERALS         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VITAMIN LIQUID          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VITAMIN W/IRON          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VITAMIN W/MINERALS      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VITAMIN WITH IRON       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VITAMINS                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VITAMINS W/IRON         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VITAMINS WITH MINERALS  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTI-VITS.                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTILEX                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIPLE VITAMIN              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVIT                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVIT W/IRON               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVIT(MOD NF               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMIN (WITH MINERALS)  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMIN & MINERAL        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMIN W/IRON           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMIN W/MINERAL        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMIN WITH IRON        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMIN WITH MINERAL     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMIN WITH MINERALS    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMINAS                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMINE W/MINERAL       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMIS&IRON             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULTIVITAMS                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULVI                         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULVI TAB (VITAMINAS)         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='MULYIVITAMIN                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NASAL SPRAY                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NASAL SPRAY DK NAME           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NATURAL FIBER LAXATIVE        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NATURAL LAX                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NATURAL LAXATIVE FIBER        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NATURAL TEARS                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NATURAL TEARS EYE DROP        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NATURAL VEG. LAX              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NATURAL VEG. LAXATIVE         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NATURAL VEGETABLE LAXATIVE    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NATURES REMEDY                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NEW GLASSES                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NOSE DROPS                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='NOSE SPRAY                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OCEAN NASAL SPRAY             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OCEAN NAZEL SPRAY             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OCEAN SPRAY & ATROPINE        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OIL                           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OLIVE OIL                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ONE A DAY VITAMINS            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ONE TOUCH GLUCOSE MONITOR     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OTC                           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OTC ITEM                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OYST-CAL                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OYST-CAL D                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OYST-CALD                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='OYSTCAL                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='PROTEIN                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='PROTEIN DRINK DK NAME         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='PROTEIN SUPPLEMENT            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='PUDDING                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='RED WINE                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ROBITUSSIN-DF                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='ROBITUSSIN-DN                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SALINE IRRIG SOLUTION         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SALINE SOLUTION               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SALT TABLET                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SALT WATER RINSE              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SELSUM GOLD SHAMPOO           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SHAKE CREAM                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SHAKE UP                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SHAKE UPS                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SHAKE-UP                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STOP GEL                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS FORMULA                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS FORMULA V              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS FORMULA VITAMINS W/ZINC' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS FORMULA W/ZINC         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS MED                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS TAB                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS TABS W/IR              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS TABS W/IRON            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS VITAMINS/C             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='STRESS-TAB                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SUN SCREEN                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SUNBLOCK                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SUNSCREEN                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SUNSCREEN LOTION              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SUPER DOOPER DIAPER DOO       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SWEET OIL                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SYRINGE                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SYRINGE/NEEDLE FOR MIACALCIM  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SYRINGER                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SYRINGES                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SYRINGES AND NEEDLES          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SYRINGES AND TEST PAPER       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='SYRINGES DISPOSABLE           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TED HOSE                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TED HOSES                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TED SOCKS                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TED STOCKINGS                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TEGRIN                        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TEGRIN-SHAMPOO                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THER MULTIVITES               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERA M                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERA MULTI VITAMIN           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERA VITAMIN                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERA-GRAM M                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERA-M                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERA-MULTI VITAMIN           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERADAX VITAMIN              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERAGAN M VITAMIN            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERAPEUTIC MULTI VITAMIN     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERAPEUTIC PLUS VIT          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERAPEUTIC VITS W/MIN        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERAPUETIC-M                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THERAVITE                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THREW AWAY BOTTLE             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='THREW BOTTLE AWAY             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYL TABS EXTRA STRENGTH       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLANOL EXTRA STRENGTH        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL E.S.                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL EC/ST                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL ES                    ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL EX STRENGTH           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL EX STRGTH             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL EX-S                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL EX-STR. TABS          ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL EXTRA ST              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL EXTRA STRENGTH        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL I                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL X                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL X STRENGTH            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL X-STRENGTH            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='TYLENOL XRA. STREN-500        ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VASELINE                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VASELINE CHAPSTICK            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VASELINE GRANULEX             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VASELINE JELLY                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VASOLINE                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VEG LAXATIVE                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME="VICK'S COUGH DROPS            " THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VICKS INHALER                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VICKS VAPO RUB                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VINEGAR DOUCHE                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VIT C SUPPLEMENT              ' THEN DO; OTCLEG='O'; END;
/*IF PMEDNAME='VIT D                         ' THEN DO; OTCLEG='O'; END;*/
IF PMEDNAME='VIT E                         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VIT. B 12                     ' THEN DO; OTCLEG='O'; END;
/*IF PMEDNAME='VIT. D                        ' THEN DO; OTCLEG='O'; END;*/
IF PMEDNAME='VITA BETA CARATENE            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITA LEA                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITA NUMONILL                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITA/MINERAL                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITA/MINERALS                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITACON FORTE                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAL K                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITALAN                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITALMINERALS                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN                       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN (HOUSE)               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN & MINERAL SUPPLEMENT  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN A CREME               ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN B                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN B COMPLEX             ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN B 1                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN B 12                  ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN BCOMPLEX              ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN BI-B6                 ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN C&B                   ' THEN DO; OTCLEG='O'; END;
/*IF PMEDNAME='VITAMIN D CAPS                ' THEN DO; OTCLEG='O'; END;*/
IF PMEDNAME='VITAMIN SUPPLEMENT            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN TAB MULTIVITAMIN      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN THERAPUTIC            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN THERERABITE           ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN WITH MINERALS         ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMIN-UNICAP                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMINAS                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMINB1                     ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMINS                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMINS WITH ZINC            ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITAMINS(FERRO SEQUELS)       ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITARINE                      ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='VITIMAN C 500MG               ' THEN DO; OTCLEG='O'; END;
/*IF PMEDNAME='VITIMIN D                     ' THEN DO; OTCLEG='O'; END;*/
IF PMEDNAME='VIYIMIN B-6                   ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='V1-DAYLIN W/FE                ' THEN DO; OTCLEG='O'; END;
IF PMEDNAME='X-STRENGTH TYLENOL            ' THEN DO; OTCLEG='O'; END;

IF       BN='INSULIN                       ' THEN DO; OTCLEG='I'; END;

IF PMEDNAME='BD U-100  INSULIN SYR         ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='HUBULIN 70/30                 ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='HUMALIN R                     ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='HUMAN INSULIN                 ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='HUMILIN N                     ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='HUMLAN LENTE                  ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='HUMULIN N 100                 ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='ILETIN                        ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='ILETIN  I REGULAR 100U        ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='ILETIN I                      ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='ILETIN I (INSULIN)            ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='ILETIN NPH                    ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='INS NPH                       ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='INS SYR LO-DOSE 1/2CC         ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='INS ULTLENT U100              ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='INSULIN PORK LENTC U          ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='LENTE                         ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='LENTE  INSULIN                ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='LENTE ILENTIN 1               ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='LENTE INSULIN                 ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='LENTE PORK                    ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='LENTE U 100                   ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='LO DOSE                       ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='LO DOSE SYRINGE               ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='N INSULATARD NPH HUMAN        ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='NEEDLES FOR INSULIN           ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='NOVALENE                      ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='NOVILIN N                     ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='NOVILIN R                     ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='NPH ILETIN                    ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='NPH ILETIN I                  ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='NPH INSULIN                   ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='NPH INSULIN HUMAN             ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='NPH U-100                     ' THEN DO; OTCLEG='I'; END;
IF PMEDNAME='REGULAR PORK INSULIN          ' THEN DO; OTCLEG='I'; END;



***  IF OTCLEG ISN'T ASSIGNED, ASSUME ITS LEGEND ***;

IF OTCLEG=' ' THEN OTCLEG='F';

***  DELETE THOSE THAT WE KNOW TO BE OTC  ***;
IF OTCLEG='O' THEN output mcbsdata.Deleted_OTC_&curryear;
			  ELSE OUTPUT ALL&CurrYear;
RUN;




/*
* THIS PART OF PROGRAM RETAINS THOSE PEOPLE WHO HAVE ROUND SIX
DRUGS THAT WE WANT TO RETAIN;
DATA COMPCODE;
INFILE VIEW;
INPUT BASEID $ 1-8 R1 $ 28-30 R2 $ 31-33 R3 $ 34-36 R4 $ 37-39
R5 $ 40-42 R6 $ 43-45;
RUN;
DATA COMPCODE;
SET COMPCODE;
CODE=R1||R2||R3||R4||R5||R6;
RUN;
DATA WHOSWHO;
SET COMPCODE;
IF R5='41C';
RUN;
PROC SORT;
BY BASEID;
RUN;
DATA RETA.RETAINS(KEEP=BASEID);
SET WHOSWHO;
RUN;
PROC PRINT;RUN;
*/


*** MAKE OTHER VARIOUS CORRECTIONS ***;
DATA INS;
SET  ALL&CurrYear;
*     INSULIN TARGET REIM ASSIGNMENTS;
* INCREASE EXPONENT BY 1 EVERY YEAR...REFLECTS 10% INCREASE;
*  IN THESE DRUGS ANNUALLY...ITS OUR BEST GUESS
* R = price * (1+.10);
*Updated 3/4/20;
IF _TREIM=. AND OTCLEG='I' THEN DO;
IF PAYFACT='R' THEN _TREIM=19.30;
IF PAYFACT='C' THEN _TREIM=18.38;
IF PAYFACT='V' THEN _TREIM=8.20;
IF PAYFACT='O' THEN _TREIM=15.20;
IF PAYFACT='H' THEN _TREIM=10.79;
IF PAYFACT NE 'R' AND PAYFACT NE 'C' AND PAYFACT NE 'V'
AND PAYFACT NE 'O' AND PAYFACT NE 'H' THEN _TREIM=15.20;
END;

*     NOTHING LESS THAN TREIM = .50;
IF _TREIM<.50 AND _TREIM NE . THEN DO;
IF FUZZ(_AMTOOP-_TREIM)>-.01 AND FUZZ(_AMTOOP-_TREIM)<.01
THEN _AMTOOP=.;
IF _SOPCARE NE 0 THEN _AMTCARE=.;
IF _SOPCAID NE 0 THEN _AMTCAID=.;
IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
IF _SOPVA   NE 0 THEN _AMTVA=.;
IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
IF _SOPDISC NE 0 THEN _AMTDISC=.;
IF _SOPOTH  NE 0 THEN _AMTOTH=.;
IF _SOPPD   NE 0 THEN _AMTPD=.;
IF _SOPMA   NE 0 THEN _AMTMA=.;
_TREIM=.50;
END;

*    NUMLINK NUMSAME PROBLEM;
IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG >0 AND PAYFACT='R' AND EVPRICE<5 THEN
DO;
 _TREIM=EVPRICE * &R_factor_LT5;
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN DO; _AMTCARE=.;END;
 IF _SOPCAID NE 0 THEN DO; _AMTCAID=.;END;
 IF _SOPpHMO  NE 0 THEN DO; _AMTpHMO=.;END;
 IF _SOPVA   NE 0 THEN DO; _AMTVA=.;END;
 IF _SOPPRVE NE 0 THEN DO; _AMTPRVE=.;END;
 IF _SOPPRVI NE 0 THEN DO; _AMTPRVI=.;END;
 IF _SOPOOP  NE 0 THEN DO; _AMTOOP=.;END;
 IF _SOPDISC NE 0 THEN DO; _AMTDISC=.;END;
 IF _SOPOTH  NE 0 THEN DO; _AMTOTH=.;END;
 IF _SOPPD   NE 0 THEN DO; _AMTPD=.;END;
 IF _SOPMA   NE 0 THEN DO; _AMTMA=.;END;
END;


IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG>0 AND PAYFACT='R' AND EVPRICE>4.99 AND EVPRICE<20 THEN
DO;
 _TREIM=EVPRICE * &R_factor_5_20;
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN _AMTCARE=.;
 IF _SOPCAID NE 0 THEN _AMTCAID=.;
 IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
 IF _SOPVA   NE 0 THEN _AMTVA=.;
 IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
 IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
 IF _SOPOOP  NE 0 THEN _AMTOOP=.;
 IF _SOPDISC NE 0 THEN _AMTDISC=.;
 IF _SOPOTH  NE 0 THEN _AMTOTH=.;
 IF _SOPPD   NE 0 THEN _AMTPD=.;
 IF _SOPMA   NE 0 THEN _AMTMA=.;
END;

IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG>0 AND PAYFACT='R' AND EVPRICE>19.99 THEN
DO;
 _TREIM=EVPRICE * &R_factor_GT20;
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN _AMTCARE=.;
 IF _SOPCAID NE 0 THEN _AMTCAID=.;
 IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
 IF _SOPVA   NE 0 THEN _AMTVA=.;
 IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
 IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
 IF _SOPOOP  NE 0 THEN _AMTOOP=.;
 IF _SOPDISC NE 0 THEN _AMTDISC=.;
 IF _SOPOTH  NE 0 THEN _AMTOTH=.;
 IF _SOPPD   NE 0 THEN _AMTPD=.;
 IF _SOPMA   NE 0 THEN _AMTMA=.;
END;

IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG>0 AND PAYFACT='E' THEN
DO;
 _TREIM=EVPRICE * &E_factor;
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN _AMTCARE=.;
 IF _SOPCAID NE 0 THEN _AMTCAID=.;
 IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
 IF _SOPVA   NE 0 THEN _AMTVA=.;
 IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
 IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
 IF _SOPOOP  NE 0 THEN _AMTOOP=.;
 IF _SOPDISC NE 0 THEN _AMTDISC=.;
 IF _SOPOTH  NE 0 THEN _AMTOTH=.;
 IF _SOPPD   NE 0 THEN _AMTPD=.;
 IF _SOPMA   NE 0 THEN _AMTMA=.;
END;

IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG>0 AND PAYFACT='H' THEN
DO;
 _TREIM=EVPRICE * &H_factor;
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN _AMTCARE=.;
 IF _SOPCAID NE 0 THEN _AMTCAID=.;
 IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
 IF _SOPVA   NE 0 THEN _AMTVA=.;
 IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
 IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
 IF _SOPOOP  NE 0 THEN _AMTOOP=.;
 IF _SOPDISC NE 0 THEN _AMTDISC=.;
 IF _SOPOTH  NE 0 THEN _AMTOTH=.;
 IF _SOPPD   NE 0 THEN _AMTPD=.;
 IF _SOPMA   NE 0 THEN _AMTMA=.;
END;

IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG>0 AND PAYFACT='V' THEN
DO;
 _TREIM=EVPRICE * &V_factor;
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN _AMTCARE=.;
 IF _SOPCAID NE 0 THEN _AMTCAID=.;
 IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
 IF _SOPVA   NE 0 THEN _AMTVA=.;
 IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
 IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
 IF _SOPOOP  NE 0 THEN _AMTOOP=.;
 IF _SOPDISC NE 0 THEN _AMTDISC=.;
 IF _SOPOTH  NE 0 THEN _AMTOTH=.;
 IF _SOPPD   NE 0 THEN _AMTPD=.;
 IF _SOPMA   NE 0 THEN _AMTMA=.;

END;

IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG>0 AND PAYFACT='C' THEN
DO;
 _TREIM=(EVPRICE * &C_factor) + (&C_PLUS);
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN _AMTCARE=.;
 IF _SOPCAID NE 0 THEN _AMTCAID=.;
 IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
 IF _SOPVA   NE 0 THEN _AMTVA=.;
 IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
 IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
 IF _SOPOOP  NE 0 THEN _AMTOOP=.;
 IF _SOPDISC NE 0 THEN _AMTDISC=.;
 IF _SOPOTH  NE 0 THEN _AMTOTH=.;
 IF _SOPPD   NE 0 THEN _AMTPD=.;
 IF _SOPMA   NE 0 THEN _AMTMA=.;
END;

IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG>0 AND PAYFACT='O' THEN
DO;
 _TREIM=(EVPRICE * &O_factor) + (&O_PLUS);
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN _AMTCARE=.;
 IF _SOPCAID NE 0 THEN _AMTCAID=.;
 IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
 IF _SOPVA   NE 0 THEN _AMTVA=.;
 IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
 IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
 IF _SOPOOP  NE 0 THEN _AMTOOP=.;
 IF _SOPDISC NE 0 THEN _AMTDISC=.;
 IF _SOPOTH  NE 0 THEN _AMTOTH=.;
 IF _SOPPD   NE 0 THEN _AMTPD=.;
 IF _SOPMA   NE 0 THEN _AMTMA=.;
END;

IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG>0 AND PAYFACT='P' THEN
DO;
 _TREIM=(EVPRICE * &P_factor) ;
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN _AMTCARE=.;
 IF _SOPCAID NE 0 THEN _AMTCAID=.;
 IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
 IF _SOPVA   NE 0 THEN _AMTVA=.;
 IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
 IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
 IF _SOPOOP  NE 0 THEN _AMTOOP=.;
 IF _SOPDISC NE 0 THEN _AMTDISC=.;
 IF _SOPOTH  NE 0 THEN _AMTOTH=.;
 IF _SOPPD   NE 0 THEN _AMTPD=.;
 IF _SOPMA   NE 0 THEN _AMTMA=.;
END;

IF NUMLINKS<0 AND NUMSAME<0 AND TOTALCHG>0 AND PAYFACT='A' THEN
DO;
 _TREIM=(EVPRICE * &A_factor) ;
 NLNS=1;
 _IMPSTAT=2;
 IF _SOPCARE NE 0 THEN _AMTCARE=.;
 IF _SOPCAID NE 0 THEN _AMTCAID=.;
 IF _SOPpHMO  NE 0 THEN _AMTpHMO=.;
 IF _SOPVA   NE 0 THEN _AMTVA=.;
 IF _SOPPRVE NE 0 THEN _AMTPRVE=.;
 IF _SOPPRVI NE 0 THEN _AMTPRVI=.;
 IF _SOPOOP  NE 0 THEN _AMTOOP=.;
 IF _SOPDISC NE 0 THEN _AMTDISC=.;
 IF _SOPOTH  NE 0 THEN _AMTOTH=.;
 IF _SOPPD   NE 0 THEN _AMTPD=.;
 IF _SOPMA   NE 0 THEN _AMTMA=.;
END;


*    OUTLIER FOR AMTPRVE = 500;
IF BASEID='00022003' AND _AMTPRVE=500 THEN DO;
_AMTPRVE=.;
_SOPPRVE=2;
END;


*    OUTLIER FOR OOPS WITHIN HMO/VA PEOPLE;
IF ID='0020054500203002' THEN _AMTOOP=8;
IF ID='0020054500203002' THEN _AMTOOP=8;
IF ID='0020054500203003' THEN _AMTOOP=8;
IF ID='0020054500203004' THEN _AMTOOP=8;
IF ID='0020054500203002' THEN _AMTOOP=8;
IF ID='0020054500203002' THEN _AMTOOP=8;
IF ID='0020054500203003' THEN _AMTOOP=8;
IF ID='0020054500203004' THEN _AMTOOP=8;
IF ID='0020054500303002' THEN _AMTOOP=8;
IF ID='0020054500303002' THEN _AMTOOP=8;
IF ID='0020054500303003' THEN _AMTOOP=8;
IF ID='0020054500303004' THEN _AMTOOP=8;
IF ID='0020054500403002' THEN _AMTOOP=8;
IF ID='0020054500403002' THEN _AMTOOP=8;
IF ID='0020054500403003' THEN _AMTOOP=8;
IF ID='0020054500403004' THEN _AMTOOP=8;
IF ID='0025110702405002' THEN _AMTOOP=10;
IF ID='0025110702405002' THEN _AMTOOP=10;
IF ID='0025110702405003' THEN _AMTOOP=10;
IF ID='0025110702405004' THEN _AMTOOP=10;
IF ID='0025110702505002' THEN _AMTOOP=10;
IF ID='0025110702505002' THEN _AMTOOP=10;
IF ID='0025110702505003' THEN _AMTOOP=10;
IF ID='0025110702505004' THEN _AMTOOP=10;
IF ID='0025110702605002' THEN _AMTOOP=10;
IF ID='0025110702605002' THEN _AMTOOP=10;
IF ID='0025110702605003' THEN _AMTOOP=10;
IF ID='0025110702605004' THEN _AMTOOP=10;
IF ID='0025110702705002' THEN _AMTOOP=10;
IF ID='0025110702705002' THEN _AMTOOP=10;
IF ID='0025110702705003' THEN _AMTOOP=10;
IF ID='0025110702705004' THEN _AMTOOP=10;
IF ID='0025110702805002' THEN _AMTOOP=10;
IF ID='0025110702805002' THEN _AMTOOP=10;
IF ID='0025110702805003' THEN _AMTOOP=10;
IF ID='0025110702805004' THEN _AMTOOP=10;

*    AMT > 0 BUT SOP FLAG =0 , TRUST SOP;
IF _SOPCARE=0 AND _AMTCARE > 0 AND _AMTCARE NE . THEN DO; _AMTCARE=0; AMTCHG=1; END;
IF _SOPCAID=0 AND _AMTCAID > 0 AND _AMTCAID NE . THEN DO; _AMTCAID=0; AMTCHG=1; END;
IF _SOPpHMO =0 AND _AMTpHMO  > 0 AND _AMTpHMO  NE . THEN DO; _AMTpHMO =0; AMTCHG=1; END;
IF _SOPVA  =0 AND _AMTVA   > 0 AND _AMTVA   NE . THEN DO; _AMTVA  =0; AMTCHG=1; END;
IF _SOPPRVE=0 AND _AMTPRVE > 0 AND _AMTPRVE NE . THEN DO; _AMTPRVE=0; AMTCHG=1; END;
IF _SOPPRVI=0 AND _AMTPRVI > 0 AND _AMTPRVI NE . THEN DO; _AMTPRVI=0; AMTCHG=1; END;
IF _SOPOOP =0 AND _AMTOOP  > 0 AND _AMTOOP  NE . THEN DO; _AMTOOP =0; AMTCHG=1; END;
IF _SOPDISC=0 AND _AMTDISC > 0 AND _AMTDISC NE . THEN DO; _AMTDISC=0; AMTCHG=1; END;
IF _SOPOTH =0 AND _AMTOTH  > 0 AND _AMTOTH  NE . THEN DO; _AMTOTH =0; AMTCHG=1; END;
IF _SOPPD  =0 AND _AMTPD   > 0 AND _AMTPD   NE . THEN DO; _AMTPD  =0; AMTCHG=1; END;
IF _SOPMA  =0 AND _AMTMA   > 0 AND _AMTMA   NE . THEN DO; _AMTMA  =0; AMTCHG=1; END;


*     SOP FLAG ON BUT AMT=0;
IF _SOPCARE=1 AND _AMTCARE = 0 THEN DO; _AMTCARE=.; END;
IF _SOPCAID=1 AND _AMTCAID = 0 THEN DO; _AMTCAID=.; END;
IF _SOPpHMO =1 AND _AMTpHMO  = 0 THEN DO; _AMTpHMO =.; END;
IF _SOPVA  =1 AND _AMTVA   = 0 THEN DO; _AMTVA  =.; END;
IF _SOPPRVE=1 AND _AMTPRVE = 0 THEN DO; _AMTPRVE=.; END;
IF _SOPPRVI=1 AND _AMTPRVI = 0 THEN DO; _AMTPRVI=.; END;
IF _SOPOOP =1 AND _AMTOOP  = 0 THEN DO; _AMTOOP =.; END;
IF _SOPDISC=1 AND _AMTDISC = 0 THEN DO; _AMTDISC=.; END;
IF _SOPOTH =1 AND _AMTOTH  = 0 THEN DO; _AMTOTH =.; END;
IF _SOPPD  =1 AND _AMTPD   = 0 THEN DO; _AMTPD  =.; END;
IF _SOPMA  =1 AND _AMTMA   = 0 THEN DO; _AMTMA  =.; END;

*     SOP FLAG=1 BUT AMT = .;
IF _SOPCARE=1 AND _AMTCARE=. THEN _SOPCARE=2;
IF _SOPCAID=1 AND _AMTCAID=. THEN _SOPCAID=2;
IF _SOPpHMO =1 AND _AMTpHMO =. THEN _SOPpHMO =2;
IF _SOPVA  =1 AND _AMTVA  =. THEN _SOPVA  =2;
IF _SOPPRVE=1 AND _AMTPRVE=. THEN _SOPPRVE=2;
IF _SOPPRVI=1 AND _AMTPRVI=. THEN _SOPPRVI=2;
IF _SOPOOP =1 AND _AMTOOP =. THEN _SOPOOP =2;
IF _SOPDISC=1 AND _AMTDISC=. THEN _SOPDISC=2;
IF _SOPOTH =1 AND _AMTOTH =. THEN _SOPOTH =2;
IF _SOPPD  =1 AND _AMTPD  =. THEN _SOPPD  =2;
IF _SOPMA  =1 AND _AMTMA  =. THEN _SOPMA  =2;

RUN;


DATA TOWESTAT_&CurrYEAR
(KEEP=BASEID EVNTNUM ROUND COSTNUM UTILNUM OTCLEG _TREIM
	  _SOPCAID _SOPPRVE _SOPOOP _SOPpHMO _SOPPRVI _SOPVA _SOPDISC _SOPCARE _SOPOTH _SOPPD _SOPMA
	  _AMTCARE _AMTCAID _AMTpHMO _AMTVA _AMTPRVE _AMTPRVI _AMTOOP _AMTDISC _AMTOTH _AMTPD _AMTMA
	  ISOPCARE ISOPCAID ISOPpHMO ISOPVA ISOPPRVE ISOPPRVI ISOPOOP ISOPDISC ISOPOTH ISOPPD ISOPMA
	  NLNS BN _IMPSTAT AMTCHG AWP INS_FLGS RX_FLGS HDPHMO HDOPUB HDPRVE HDPRVI
	  HDRX XTRAS  PMSUMFLG EV95FLG);

SET INS;
*     SOP FLAG=0 BUT AMT=.;
IF _SOPCARE=0 AND _AMTCARE=. THEN _AMTCARE=0;
IF _SOPCAID=0 AND _AMTCAID=. THEN _AMTCAID=0;
IF _SOPpHMO =0 AND _AMTpHMO =. THEN _AMTpHMO =0;
IF _SOPVA  =0 AND _AMTVA  =. THEN _AMTVA  =0;
IF _SOPPRVE=0 AND _AMTPRVE=. THEN _AMTPRVE=0;
IF _SOPPRVI=0 AND _AMTPRVI=. THEN _AMTPRVI=0;
IF _SOPOOP =0 AND _AMTOOP =. THEN _AMTOOP =0;
IF _SOPDISC=0 AND _AMTDISC=. THEN _AMTDISC=0;
IF _SOPOTH =0 AND _AMTOTH =. THEN _AMTOTH =0;
IF _SOPPD  =0 AND _AMTPD  =. THEN _AMTPD  =0;
IF _SOPMA  =0 AND _AMTMA  =. THEN _AMTMA  =0;

RUN;


**RE-SORT COLUMNS AND MAKE PERMANENT;
proc sql;
create table MCBSDATA.TOWESTAT_&CurrYEAR
as select
BASEID,
EVNTNUM,
ROUND,
UTILNUM,
COSTNUM,
_SOPCARE,
_SOPCAID,
_SOPpHMO,
_SOPVA,
_SOPPRVE,
_SOPPRVI,
_SOPOOP,
_SOPDISC,
_SOPOTH,
_SOPPD,
_SOPMA,
_AMTCARE,
_AMTCAID,
_AMTpHMO,
_AMTVA,
_AMTPRVE,
_AMTPRVI,
_AMTOOP,
_AMTDISC,
_AMTOTH,
_AMTPD,
_AMTMA,
ISOPCARE,
ISOPCAID,
ISOPpHMO,
ISOPVA,
ISOPPRVE,
ISOPPRVI,
ISOPOOP,
ISOPDISC,
ISOPOTH,
ISOPPD,
ISOPMA,
OTCLEG,
_TREIM,
_IMPSTAT,
NLNS,
AMTCHG,
AWP,
EV95FLG,
PMSUMFLG,
INS_FLGS,
RX_FLGS,
HDPHMO,
HDOPUB,
HDPRVE,
HDPRVI,
HDRX,
XTRAS,
BN
from TOWESTAT_&CurrYEAR;
quit;



ODS RTF BODYTITLE FILE="&LOCATION.OUTPUT\TO WESTAT FILE STATISTICS 20&CURRYEAR VS 20&LASTYEAR - %sysfunc(DATE(),mmddYYd10.).RTF";
TITLE "20&curryear";
PROC FREQ data=MCBSDATA.TOWESTAT_&curryear;
TABLE _IMPSTAT NLNS AMTCHG;
run;title;

TITLE "20&lastyear";
PROC FREQ DATA=MCBSLAST.TOWESTAT_&lastyear;
TABLE _IMPSTAT NLNS AMTCHG;
run;title;


TITLE "20&curryear";
proc means data=MCBSDATA.TOWESTAT_&curryear N NMISS MEAN STD sum MIN MAX MAXDEC=2;
VAR _AMTOOP _AMTCAID _AMTCARE _AMTpHMO _AMTVA _AMTPRVE _AMTPRVI _AMTDISC _AMTOTH _AMTPD _AMTMA _TREIM
    _SOPOOP _SOPCAID _SOPCARE _SOPpHMO _SOPVA _SOPPRVE _SOPPRVI _SOPDISC _SOPOTH _SOPPD _SOPMA _IMPSTAT AWP;
run;TITLE;

TITLE "20&lastyear";
proc means data=MCBSLAST.TOWESTAT_&lastyear N NMISS MEAN STD  sum MIN MAX sum MAXDEC=2;
VAR _AMTOOP _AMTCAID _AMTCARE _AMTpHMO _AMTVA _AMTPRVE _AMTPRVI _AMTDISC _AMTOTH _AMTPD _AMTMA _TREIM
    _SOPOOP _SOPCAID _SOPCARE _SOPPHMO _SOPVA _SOPPRVE _SOPPRVI _SOPDISC _SOPOTH _SOPPD _SOPMA _IMPSTAT AWP;
run;TITLE;


DATA W20&curryear;
SET MCBSDATA.TOWESTAT_&CURRYEAR
	(KEEP=BN    _AMTOOP _AMTCAID _AMTCARE _AMTpHMO _AMTVA _AMTPRVE _AMTPRVI _AMTDISC _AMTOTH _AMTPD _AMTMA
         _TREIM _SOPOOP _SOPCAID _SOPCARE _SOPpHMO _SOPVA _SOPPRVE _SOPPRVI _SOPDISC _SOPOTH _SOPPD _SOPMA 
         _IMPSTAT AWP);
PAYOR_TOTAL=SUM(_AMTOOP, _AMTCAID, _AMTCARE, _AMTpHMO, _AMTVA, _AMTPRVE, _AMTPRVI, _AMTDISC, _AMTOTH,_AMTPD, _AMTMA );
YEAR="20&curryear";
RUN;
DATA W20&lastyear;
SET MCBSLAST.TOWESTAT_&LASTYEAR
	(KEEP=BN    _AMTOOP _AMTCAID _AMTCARE _AMTpHMO _AMTVA _AMTPRVE _AMTPRVI _AMTDISC _AMTOTH _AMTPD _AMTMA
         _TREIM _SOPOOP _SOPCAID _SOPCARE _SOPpHMO _SOPVA _SOPPRVE _SOPPRVI _SOPDISC _SOPOTH _SOPPD _SOPMA 
         _IMPSTAT AWP);

PAYOR_TOTAL=SUM(_AMTOOP, _AMTCAID, _AMTCARE, _AMTpHMO, _AMTVA, _AMTPRVE, _AMTPRVI, _AMTDISC, _AMTOTH,_AMTPD, _AMTMA );
YEAR="20&lastyear";

RUN;

DATA W;
SET W20&curryear W20&lastyear;
RUN;
title "Costs by Year";
PROC TABULATE DATA=WORK.W   order=freq;
   VAR PAYOR_TOTAL
   _AMTOOP _AMTCAID _AMTCARE _AMTpHMO _AMTVA _AMTPRVE _AMTPRVI _AMTDISC _AMTOTH _AMTPD _AMTMA _TREIM
   _SOPOOP _SOPCAID _SOPCARE _SOPpHMO _SOPVA _SOPPRVE _SOPPRVI _SOPDISC _SOPOTH _SOPPD _SOPMA _IMPSTAT AWP;
   CLASS YEAR;
   TABLE (PAYOR_TOTAL
         _AMTOOP _AMTCAID _AMTCARE _AMTpHMO _AMTVA _AMTPRVE _AMTPRVI _AMTDISC _AMTOTH _AMTPD _AMTMA _TREIM
         _SOPOOP _SOPCAID _SOPCARE _SOPpHMO _SOPVA _SOPPRVE _SOPPRVI _SOPDISC _SOPOTH _SOPPD _SOPMA _IMPSTAT AWP ),
          (YEAR) *
			 ('N'='N'
			  'SUM'='Sum'
              'MEAN'='Mean'
			  'MEDIAN'='Median')  / misstext=' ';
RUN;title;

title "Targeted Reimbursement Amounts by Drug By Year";
PROC TABULATE DATA=WORK.W   order=freq;
   VAR _treim;
   CLASS BN YEAR;
   TABLE BN ,
		 (YEAR) * (_treim) *
			 ('N'='N'
			  'MEAN'='Mean'
			  'MEDIAN'='Median')  / misstext=' ';
RUN;title;


title "Deleted OTC products";
proc freq data=mcbsdata.Deleted_OTC_&curryear order=freq;
tables bn;
run;title;


ODS RTF CLOSE;

%put ENDED ON %sysfunc(DATE(),mmddyyd10.) AT: %sysfunc(TIME(),timeampm8.);



